import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agile Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider basePath="http://localhost:3000/api/auth">
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
